name: Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/**'

env:
  NODE_VERSION: '18.x'
  PNPM_VERSION: '8.x'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
        cache-dependency-path: 'shadcn-ui/pnpm-lock.yaml'

    - name: Install dependencies
      working-directory: ./shadcn-ui
      run: pnpm install --frozen-lockfile

    - name: Build application
      working-directory: ./shadcn-ui
      run: pnpm build

    - name: Run tests
      working-directory: ./shadcn-ui
      run: pnpm test --if-present

    - name: Generate changelog
      id: changelog
      run: |
        # Get the latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $LATEST_TAG"
        
        # Generate changelog since last tag
        CHANGELOG=$(git log --pretty=format:"- %s (%an)" ${LATEST_TAG}..HEAD --no-merges | head -20)
        
        if [ -z "$CHANGELOG" ]; then
          CHANGELOG="- Initial release"
        fi
        
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Determine version bump
      id: version
      run: |
        # Get commit messages since last tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        COMMITS=$(git log --pretty=format:"%s" ${LATEST_TAG}..HEAD --no-merges)
        
        # Determine version bump type
        if echo "$COMMITS" | grep -qiE "^(feat|feature)(\(.+\))?!:|^.+!:|BREAKING CHANGE:"; then
          VERSION_TYPE="major"
        elif echo "$COMMITS" | grep -qiE "^(feat|feature)(\(.+\))?:"; then
          VERSION_TYPE="minor"
        elif echo "$COMMITS" | grep -qiE "^(fix|bugfix|patch)(\(.+\))?:|^(docs|style|refactor|test|chore)(\(.+\))?:"; then
          VERSION_TYPE="patch"
        else
          VERSION_TYPE="patch"
        fi
        
        echo "VERSION_TYPE=$VERSION_TYPE" >> $GITHUB_OUTPUT
        echo "Detected version type: $VERSION_TYPE"

    - name: Create release tag
      id: tag
      run: |
        # Get current version
        CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        
        # Remove 'v' prefix for version calculation
        CURRENT_VERSION_NUM=${CURRENT_VERSION#v}
        
        # Split version into components
        IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION_NUM"
        MAJOR=${VERSION_PARTS[0]:-0}
        MINOR=${VERSION_PARTS[1]:-0}
        PATCH=${VERSION_PARTS[2]:-0}
        
        # Increment version based on type
        case "${{ steps.version.outputs.VERSION_TYPE }}" in
          "major")
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
          "minor")
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
          "patch")
            PATCH=$((PATCH + 1))
            ;;
        esac
        
        NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "New version: $NEW_VERSION"
        
        # Create and push tag
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a $NEW_VERSION -m "Release $NEW_VERSION"
        git push origin $NEW_VERSION

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.NEW_VERSION }}
        name: Release ${{ steps.tag.outputs.NEW_VERSION }}
        body: |
          ## Changes in ${{ steps.tag.outputs.NEW_VERSION }}
          
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## 🚀 Deployment
          
          This release has been automatically deployed to production.
          
          ## 📊 Metrics
          
          - **Build Status**: ✅ Passed
          - **Tests**: ✅ All tests passing
          - **Security Scan**: ✅ No vulnerabilities detected
          - **Version Type**: ${{ steps.version.outputs.VERSION_TYPE }}
          
          ---
          
          *This release was automatically generated by [GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})*
        draft: false
        prerelease: false
        files: |
          shadcn-ui/dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update version in package.json
      working-directory: ./shadcn-ui
      run: |
        NEW_VERSION="${{ steps.tag.outputs.NEW_VERSION }}"
        VERSION_NUM=${NEW_VERSION#v}
        
        # Update package.json version
        npx json -I -f package.json -e "this.version='$VERSION_NUM'"
        
        # Commit and push version update
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add package.json
        git commit -m "chore: bump version to $NEW_VERSION [skip ci]" || exit 0
        git push origin main

    - name: Deploy release to production
      run: |
        echo "🚀 Deploying release ${{ steps.tag.outputs.NEW_VERSION }} to production..."
        # Add your production deployment commands here
        # Example: Deploy to AWS, Vercel, Netlify, etc.

    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Release ${{ steps.tag.outputs.NEW_VERSION }} deployed successfully"
        # Add notification logic here (Slack, Discord, email, etc.)
        # curl -X POST -H 'Content-type: application/json' \
        #   --data '{"text":"🚀 NoblePay '${{ steps.tag.outputs.NEW_VERSION }}' deployed to production!"}' \
        #   ${{ secrets.SLACK_WEBHOOK_URL }}

  cleanup:
    name: Cleanup Old Releases
    runs-on: ubuntu-latest
    needs: release
    if: success()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Delete old releases
      run: |
        # Keep only the last 10 releases
        RELEASES=$(gh release list --limit 100 --json tagName --jq '.[].tagName' | tail -n +11)
        
        for release in $RELEASES; do
          echo "Deleting old release: $release"
          gh release delete $release --yes || true
          git push --delete origin $release || true
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}